first_homepage:
    path:     /
    defaults: { _controller: FirstBundle:Default:index }
    
test_twig_extends:
    path:     /test-twig_extend
    defaults: { _controller: FirstBundle:Default:testTwigExtends }
    
test_twig_filter:
    path:     /test_twig_filter
    defaults: { _controller: FirstBundle:Default:testTwigFilter }
    
test_add_action:
    path:     /test_add_action
    defaults: { _controller: FirstBundle:Default:createCurso }
    
test_listcourses_action:
    path:     /listcourses
    defaults: { _controller: FirstBundle:Default:listCourses }

test_updatecourses_action:
    path:     /updatecourse/{id}/{name}/{description}/{price}
    defaults: { _controller: FirstBundle:Default:updateCourse }
    
test_deletecourses_action:
    path:     /deletecourse/{id}
    defaults: { _controller: FirstBundle:Default:deleteCourse }
    
test_find_action:
    path:     /find
    defaults: { _controller: FirstBundle:Default:findCourse }
    
test_nativesql_action:
    path:     /nativesql
    defaults: { _controller: FirstBundle:Default:nativeSQL }
    
test_nativedql_action:
    path:     /nativedql
    defaults: { _controller: FirstBundle:Default:nativeDQL }
