services:
    app.twig_filter_helper:
        class: FirstBundle\Twig\FilterVista
        public: true
        tags:
            - { name: twig.extension }
#    first.example:
#        class: FirstBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]