BlogBundle\Entity\Category:
    type: entity
    table: category
    indexes:
        name:
            columns:
                - name
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
    lifecycleCallbacks: {  }
