BlogBundle\Entity\User:
    type: entity
    table: user
    indexes:
        email:
            columns:
                - email
    uniqueConstraints:
        login:
            columns:
                - login
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
        passwd:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
