<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMoiykpw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMoiykpw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMoiykpw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMoiykpw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMoiykpw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Moiykpw',
    'container.build_id' => 'a5ca000a',
    'container.build_time' => 1521467180,
));
