<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2dprnfd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2dprnfd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2dprnfd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2dprnfd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2dprnfd\appDevDebugProjectContainer(array(
    'container.build_hash' => '2dprnfd',
    'container.build_id' => '08d855a9',
    'container.build_time' => 1521035951,
));
